

version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: 172.22.34.89
    dns: ivanet.net
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
        SMTP_USER = ""
        SMTP_PASS = ""
    ports:
#      - "443:443"
      - "8880:80"
      - "8822:22"
      - "587:587"
      - "7000:7000"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
      - gitlab-log:/var/log/gitlab:rw
      - gitlab-backup:/var/opt/gitlab/backups
    restart: always

volumes:
  gitlab-data:
#    external: true
  gitlab-config:
#    external: true
  gitlab-log:
#    external: true
  gitlab-backup:
#    external: true

