version: '2'
services:
  umsl-app:
    image: umsl
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application

    ports:
      - 8080:8081

    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: fluentd.umsl-app.{{.ID}}
