version: '2'

services:
  jenkins-master:
    image: jenkins-master
   
    ports:
      - "8880:8080"
      - "50000:50000"
      
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  jenkins-log
  jenkins-data

 
