ARG GRAFANA_VERSION="latest"

FROM grafana/grafana:6.2.2

USER root

#create the provisioning paths and setting permissions in the Dockerfile resolves permission issue which comes in default grafana image
# Build provisioning paths
RUN mkdir -p /etc/grafana/provisioning/notifiers && \
    mkdir -p /etc/grafana/provisioning/datasources && \
    mkdir -p /etc/grafana/provisioning/dashboards && \
    chmod -R 755 /etc/grafana/provisioning

# Assert permissions
RUN chown -R grafana:grafana /etc/grafana/ 

USER grafana

ARG GF_INSTALL_PLUGINS=""

RUN if [ ! -z "${GF_INSTALL_PLUGINS}" ]; then \
    OLDIFS=$IFS; \
        IFS=','; \
    for plugin in ${GF_INSTALL_PLUGINS}; do \
        IFS=$OLDIFS; \
        grafana-cli --pluginsDir "$GF_PATHS_PLUGINS" plugins install ${plugin}; \
    done; \
fi
